// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1nEnE3z40Vv7AkbOKk9Fe2QCNs4aGSg',
    appId: '1:198866228180:web:86e6e49b598c3e7f7bfc41',
    messagingSenderId: '198866228180',
    projectId: 'degrowth-diary',
    authDomain: 'degrowth-diary.firebaseapp.com',
    storageBucket: 'degrowth-diary.firebasestorage.app',
    measurementId: 'G-JERMT8MPY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9Z_-LEu1pYtU2B-peIpkFxbTViEl6lM',
    appId: '1:198866228180:android:ad703f0dc52c24f97bfc41',
    messagingSenderId: '198866228180',
    projectId: 'degrowth-diary',
    storageBucket: 'degrowth-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Pm4XWOZO1_m-lhtS6_PgrtdsShmaZko',
    appId: '1:198866228180:ios:6bbdbb8d47df2e7e7bfc41',
    messagingSenderId: '198866228180',
    projectId: 'degrowth-diary',
    storageBucket: 'degrowth-diary.firebasestorage.app',
    iosBundleId: 'com.degrowth.degrowthDiary',
  );
}
